### ISSUE TITLE
transfer plugin

### ISSUE THREAD

**Issue by bwp91** [joeyhage/homebridge-spotify-speaker#27]
*deletes template*

hi @poblouin 

if you are no longer maintaining this plugin, please consider transferring it to the homebridge repo where we can start the process of finding a new owner for the plugin

https://github.com/homebridge/unmaintained-plugins

**Comment by poblouin** [comment]
Hey! Sure, I didn't know that this existed. I'll do the transfer now, thanks for letting me know.

**Comment by bwp91** [comment]
Hi @poblouin 

Apologies at the time I did not realise that the npm package was published under your username scope `@poblouin/`.

I don't really feel comfortable transferring anything 'scoped' to you to another user. It just doesn't make sense!

So - just regarding the npm package (not the github repo) - how would you like me to proceed?
- very happy to transfer it back to you, or
- we can keep it in the homebridge unmaintained group, i guess for eternity!

**Comment by poblouin** [comment]
Hey @bwp91, good point, I haven't thought of that. I guess we should keep it in the homebridge group because if you transfer it back to me I'll have to deploy new versions to npm right?

**Comment by bwp91** [comment]
Yep happy to keep it with homebridge. Just obviously wanted to give you the option here!
